# https://catzkorn.dev/blog/postgres-github-actions/#goyml
name: Api IBPR Website

on:
  push:
    branches:
      - master
      - test_github_pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    #postgres db
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and publish API
      run: |
        dotnet build
        dotnet publish -c Release -o ./publish
    
    - name: Test
      run: dotnet test

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAGES_TOKEN  }}
        publish_dir: ./Api.IBPR.Website.WebAPI/bin/Release/net6.0/publish/
    
    env:
      DATABASE_DSN: "user=postgres host=localhost password=postgres port=5432 database=postgres sslmode=disable"
